// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWD2-WYr9r7AbOMM6GwJPnzR5x5-A0AmE',
    appId: '1:612710161167:web:fcf0a14274901799b5fc7a',
    messagingSenderId: '612710161167',
    projectId: 'hackkorea2022',
    authDomain: 'hackkorea2022.firebaseapp.com',
    storageBucket: 'hackkorea2022.appspot.com',
    measurementId: 'G-TR841FVR0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ugHrfczLI_8tUEnzzPmBqRXEzG2zA0M',
    appId: '1:612710161167:android:962aa7ac1ddc8525b5fc7a',
    messagingSenderId: '612710161167',
    projectId: 'hackkorea2022',
    storageBucket: 'hackkorea2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHawg1nw86_0TGP0pN43E3TG3JVbVCMaU',
    appId: '1:612710161167:ios:23f5cec32939dce2b5fc7a',
    messagingSenderId: '612710161167',
    projectId: 'hackkorea2022',
    storageBucket: 'hackkorea2022.appspot.com',
    androidClientId: '612710161167-njps0bl5kic12ev7qu5k4b0fhngie86m.apps.googleusercontent.com',
    iosClientId: '612710161167-ebo62s939skdc203o7ppqg5vg33v9klc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackkorea2022',
  );
}
